//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Monlic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contactos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contactos()
        {
            this.Movimientos = new HashSet<Movimientos>();
            this.MovimientoESA = new HashSet<MovimientoESA>();
        }
    
        public int IdContacto { get; set; }
        public string Contacto { get; set; }
        public Nullable<int> Documento { get; set; }
        public Nullable<int> Telefono { get; set; }
        public Nullable<int> IdTipoD { get; set; }
        public Nullable<int> IdCiudad { get; set; }
        public string Estado { get; set; }
    
        public virtual Ciudades Ciudades { get; set; }
        public virtual TiposDocumentos TiposDocumentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimientos> Movimientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoESA> MovimientoESA { get; set; }
    }
}
