//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Monlic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materiales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materiales()
        {
            this.Entradas_Salidas = new HashSet<Entradas_Salidas>();
            this.MovimientoESADet = new HashSet<MovimientoESADet>();
        }
    
        public int IdMaterial { get; set; }
        public string Material { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Existencia { get; set; }
        public Nullable<int> Precio { get; set; }
        public Nullable<int> IdUnidad { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entradas_Salidas> Entradas_Salidas { get; set; }
        public virtual UnidadMedidas UnidadMedidas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoESADet> MovimientoESADet { get; set; }
    }
}
