//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Monlic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoESADet
    {
        public int IdMovimientoESADet { get; set; }
        public Nullable<int> IdMovimientoESA { get; set; }
        public Nullable<int> IdMaterial { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> Cargos { get; set; }
        public Nullable<decimal> Descuentos { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual Materiales Materiales { get; set; }
        public virtual MovimientoESA MovimientoESA { get; set; }
    }
}
