//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Monlic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoESA
    {
        public int IdMovimientoESA { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Precio { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> IdMaterial { get; set; }
        public Nullable<int> IdTipoM { get; set; }
        public Nullable<int> IdContacto { get; set; }
        public string Estado { get; set; }
    
        public virtual Contactos Contactos { get; set; }
        public virtual Materiales Materiales { get; set; }
        public virtual TiposMovimientos TiposMovimientos { get; set; }
    }
}
