//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Monlic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoESA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovimientoESA()
        {
            this.MovimientoESADet = new HashSet<MovimientoESADet>();
        }
    
        public int IdMovimientoESA { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdTipoM { get; set; }
        public Nullable<int> IdContacto { get; set; }
        public string Estado { get; set; }
        public Nullable<decimal> SubTotalGeneral { get; set; }
        public Nullable<decimal> CargosGenerales { get; set; }
        public Nullable<decimal> DescuentosGenerales { get; set; }
        public Nullable<decimal> TotalGeneral { get; set; }
    
        public virtual Contactos Contactos { get; set; }
        public virtual TiposMovimientos TiposMovimientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoESADet> MovimientoESADet { get; set; }
    }
}
